CREATE DATABASE paodango;

USE paodango;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE padeiro(
    id_padeiro INT AUTO_INCREMENT PRIMARY KEY,
    nome_padeiro VARCHAR(100) NOT NULL,
    email_padeiro VARCHAR(150) NOT NULL UNIQUE,
    CPF_padeiro VARCHAR(11) NOT NULL UNIQUE,
    telefone_padeiro VARCHAR(15) NOT NULL,
    created_at_padeiro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)